version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_app
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy_net
    labels:
      caddy: http://portainer.example.com
      caddy.reverse_proxy: "portainer_app:9000"
      caddy.reverse_proxy.header_up: "X-Forwarded-Proto https"

volumes:
  portainer_data: {}

networks:
  caddy_net:
    external: true
